#!/usr/bin/env bash

#-----------------------------------------------------------------------#
# handleError:

# to be able to exit entire program from within function
trap "exit 1" TERM
export TOP_PID=$$

handleError () {
  if [ $# -ne 1 ]; then
    1="Unknown error"
  fi

  echo -e "\nError: $1\n"
  kill -s TERM $TOP_PID
}

#-----------------------------------------------------------------------#
# dumpFind: check directory & dump recursive file/folder list
# $1 = root path                       ie, /media/4000/Audio
# $2 = file/dir                        ie, f or d
# $3 = label                           ie, files-latest

dumpFind () {
  if [ $# -eq 3 ]; then
    # check that directory exists
    if [ -d "$1" ]; then
      # save recursive file/dir list to file (ignore hidden)
      # -printf '%P\n' removes the proceeding ./
      if [ "$2" = "f" ]; then
        find "$1" -not -path '*/\.*' -printf '%P\n' | \
        sort > "$1/.emcs-$label-$3"
      elif [ "$2" = "d" ]; then
        find "$1" -type d -links 2 -not -path '*/\.*' \
        -printf '%P\n' | sort > "$1/.emcs-$label-$3"
      else
        handleError "mode: file(f) or directory(d) not specified"
      fi
    else
      handleError "'$1' is not a directory"
    fi
  else
    handleError "Lack of args to 'dumpFind'"
  fi
}

#-----------------------------------------------------------------------#
# removeF: remove file or folder
# $1 = file/folder path                ie, /media/4000/Audio/Phish/...
# $2 = simulate/delete                 ie, 0=simulate 1=delete

removeF () {
  arg=("$@")
  if [ $# -eq 2 ]; then
    # if file or directory exists
    if [ -d "$1" ] || [ -e "$1" ]; then
      # if not a simulation
      if [ "$2" -eq "1" ]; then
        # delete folder/file
        if [ -d "$1" ]; then
          rm -r "$1"
        elif [ -e "$1" ]; then
          rm "$1"
        fi
      fi
      echo -e "$1" # return this value
    fi
  else
    handleError "Lack of args to 'removeF'"
  fi
}

#-----------------------------------------------------------------------#
# determineDeleted:
# $1 = root path                       ie, /media/4000/Audio

determineDeleted () {
  dumpFind "$1" "f" "files-latest"

  if [ -e "$1/.emcs-$label-files" ]; then
    # exists in 'files', but not in 'files-latest'
    comm -13 "$1/.emcs-$label-files-latest" "$1/.emcs-$label-files" \
    > "$1/.emcs-$label-deleted"
  fi

  rm "$1/.emcs-$label-files-latest"
}

#-----------------------------------------------------------------------#
# removeDeleted: remove from one location what's not in another
# $1 = root path                       ie, /media/4000/Audio
# $2 = other path                      ie, /media/4001/Audio

removeDeleted () {
  determineDeleted "$1"

  if [ -e "$1/.emcs-$label-deleted" ] &&
     [ $(stat -c%s "$1/.emcs-$label-deleted") -gt "0" ]; then

    # simulate delete
    count="0"
    echo -e "Simulate delete from '$2':"
    while read line
    do
      items=("$2/$line" 0)
      r=`removeF "${items[@]}"`

      if [[ "$r" != "" ]]; then
        count=$((count+1))
        echo "$count: $r"
      fi
    done < "$1/.emcs-$label-deleted"

    # actual delete
    if [ "$count" -gt "0" ]; then
      read -p "Actually delete these files/folders? " -n 1 -r
      echo ""
      if [[ $REPLY =~ ^[Yy]$ ]]; then
        while read line
        do
          items=("$2/$line" 1)
          removeF "${items[@]}"
        done < "$1/.emcs-$label-deleted"
      fi
    fi
  else
    echo -e "Nothing to delete from '$2'"
  fi

  if [ -e "$1/.emcs-$label-deleted" ]; then
    rm "$1/.emcs-$label-deleted"
  fi
}

#-----------------------------------------------------------------------#
# mostRecentlyUpdated: most recently updated file within folder
# $1 = path                            ie, /media/4000/Audio

mostRecentlyUpdated() {
  find "$1" -type f -exec stat \{} --printf="%Y\n" \; \
    | sort -r | head -n 1
}

#-----------------------------------------------------------------------#
# updateModified: update existing dirs by last modified date

updateModified() {
  dumpFind "$dir1" "d" "dirs"
  dumpFind "$dir2" "d" "dirs"

  # common paths found in both
  comm -12 "$dir1/.emcs-$label-dirs" "$dir2/.emcs-$label-dirs" \
    > "$dir1/.emcs-$label-update"

  # remove dumps
  rm "$dir1/.emcs-$label-dirs"; rm "$dir2/.emcs-$label-dirs"

  while read folder
  do
    # which folder most recently modified
    dir1update=`mostRecentlyUpdated "$dir1/$folder"`
    dir2update=`mostRecentlyUpdated "$dir2/$folder"`

    if [ "$dir1update" = "" ]; then dir1update="0"; fi
    if [ "$dir2update" = "" ]; then dir2update="0"; fi

    if [ "$dir1update" -gt "$dir2update" ]; then
      # dir1 is newer
      echo -e "\nUpdating: $dir2/$folder"
      rsync -r -t -v --exclude=".*" "$dir1/$folder/" "$dir2/$folder"
    elif [ "$dir2update" -gt "$dir1update" ]; then
      # dir2 is newer
      echo -e "\nUpdating: $dir1/$folder"
      rsync -r -t -v --exclude=".*" "$dir2/$folder/" "$dir1/$folder"
    fi
  done < "$dir1/.emcs-$label-update"

  rm "$dir1/.emcs-$label-update"
}

#-----------------------------------------------------------------------#
# main program

# check for minimum required arguments
if [ $# -ne 3 ]; then
  echo -e "\nUsage: emcs [label] [location1] [location2]\n"; exit 1
fi

# save label to be used globally
label=$1

# check first path
dir1=`echo $2 | sed -e 's/\/$//'`
if [ ! -d "$dir1" ]; then
  echo -e "\nError: '$dir1' is not a directory.\n"; exit 1
fi

# check second path
dir2=`echo $3 | sed -e 's/\/$//'`
if [ ! -d "$dir2" ]; then
  echo -e "\nError: '$dir2' is not a directory.\n"; exit 1
fi

echo -e "\nEvolving Music Collection Synchronization (emcs):"
echo -e "Label: $label"
echo -e "Dir1: $dir1"
echo -e "Dir2: $dir2"

echo -e "\nChecking for intentionally deleted files..."

# remove intentionally deleted files
removeDeleted "$dir1" "$dir2"
removeDeleted "$dir2" "$dir1"

echo -e "\nUpdating modified files..."
updateModified

# ignore hidden files & folders: --exclude=".*"

echo -e "\nSyncrhonizing  to '$dir2'"
rsync -r -t -v --size-only --exclude=".*" "$dir1/" "$dir2"

echo -e "\nSyncrhonizing  to '$dir1'"
rsync -r -t -v --size-only --exclude=".*" "$dir2/" "$dir1"

echo -e "\nSaving updated file list..."
dumpFind "$dir1" "f" "files"
cp -f "$dir1/.emcs-$label-files" "$dir2/.emcs-$label-files"

echo -e "\nFinished."
